version: "3.9"

services:
  excel-to-word:
    build: .
    container_name: excel-to-word
    ports:
      - "${PORT:-3002}:3002"
    environment:
      - RUST_LOG=info
      - PORT=3002
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

